export function TermsContent() {
  return (
    <div className="prose dark:prose-invert max-w-none space-y-4">
      <p>
        Welcome to AutoPilot AI. By using our services, you agree to these terms. Please read them carefully.
      </p>

      <h3 className="text-lg font-bold text-neutral-900 dark:text-neutral-50 mb-2">1. Acceptance of Terms</h3>
      <p>
        By accessing or using our platform, you agree to be bound by these Terms of Service and all applicable laws and regulations.
      </p>

      <h3 className="text-lg font-bold text-neutral-900 dark:text-neutral-50 mb-2 mt-4">2. Use License</h3>
      <p>
        Permission is granted to temporarily download one copy of the materials (information or software) on AutoPilot AI's website for personal, non-commercial transitory viewing only.
      </p>

      <h3 className="text-lg font-bold text-neutral-900 dark:text-neutral-50 mb-2 mt-4">3. Disclaimer</h3>
      <p>
        The materials on AutoPilot AI's website are provided on an 'as is' basis. AutoPilot AI makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
      </p>

      <h3 className="text-lg font-bold text-neutral-900 dark:text-neutral-50 mb-2 mt-4">4. AI Generated Content</h3>
      <p>
        Our services utilize Artificial Intelligence to generate content and analysis. You acknowledge that AI systems may occasionally produce incorrect or misleading information ("hallucinations"). You are responsible for verifying any critical information generated by the system.
      </p>

      <h3 className="text-lg font-bold text-neutral-900 dark:text-neutral-50 mb-2 mt-4">5. Limitations</h3>
      <p>
        In no event shall AutoPilot AI or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on AutoPilot AI's website.
      </p>
    </div>
  );
}
