'use client';

import { useState } from 'react';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';

interface Note {
  id: string;
  title: string;
  content: string;
  author: string;
  timestamp: string;
  tags?: string[];
  isAISummary?: boolean;
}

interface NotesPanelProps {
  notes: Note[];
  onAddNote?: (title: string, content: string) => void;
  onDeleteNote?: (noteId: string) => void;
  onGenerateAISummary?: () => void;
  readonly?: boolean;
}

export function NotesPanel({
  notes,
  onAddNote,
  onDeleteNote,
  onGenerateAISummary,
  readonly = false,
}: NotesPanelProps) {
  const [isAddingNote, setIsAddingNote] = useState(false);
  const [noteTitle, setNoteTitle] = useState('');
  const [noteContent, setNoteContent] = useState('');
  const [expandedNotes, setExpandedNotes] = useState<Set<string>>(new Set());

  const toggleExpanded = (id: string) => {
    const newExpanded = new Set(expandedNotes);
    if (newExpanded.has(id)) {
      newExpanded.delete(id);
    } else {
      newExpanded.add(id);
    }
    setExpandedNotes(newExpanded);
  };

  const handleAddNote = () => {
    if (noteTitle.trim() && noteContent.trim()) {
      onAddNote?.(noteTitle, noteContent);
      setNoteTitle('');
      setNoteContent('');
      setIsAddingNote(false);
    }
  };

  const aiSummaryNote = notes.find((n) => n.isAISummary);
  const regularNotes = notes.filter((n) => !n.isAISummary);

  return (
    <div className="space-y-4">
      {/* AI Summary Section */}
      {aiSummaryNote && (
        <Card className="border-accent/30 bg-accent/5">
          <CardHeader
            title="AI Summary"
            action={<Badge variant="accent">Auto-generated</Badge>}
          />
          <CardBody className="space-y-3">
            <p className="text-sm text-neutral-700 dark:text-neutral-300">
              {aiSummaryNote.content}
            </p>
            <p className="text-xs text-neutral-500 dark:text-neutral-400">
              Generated by {aiSummaryNote.author} • {aiSummaryNote.timestamp}
            </p>
          </CardBody>
        </Card>
      )}

      {/* Generate AI Summary Button */}
      {!readonly && !aiSummaryNote && onGenerateAISummary && (
        <Button
          variant="outline"
          className="w-full"
          onClick={onGenerateAISummary}
        >
          ✨ Generate AI Summary
        </Button>
      )}

      {/* Add Note Section */}
      {!readonly && (
        <>
          {!isAddingNote ? (
            <Button
              variant="outline"
              className="w-full"
              onClick={() => setIsAddingNote(true)}
            >
              + Add Note
            </Button>
          ) : (
            <Card className="border-accent/30 bg-accent/5">
              <CardBody className="space-y-3">
                <input
                  type="text"
                  placeholder="Note title"
                  value={noteTitle}
                  onChange={(e) => setNoteTitle(e.target.value)}
                  className="w-full px-3 py-2 bg-white dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-700 rounded-lg text-sm font-medium text-neutral-900 dark:text-neutral-50 placeholder-neutral-500 dark:placeholder-neutral-400 focus:outline-2 focus:outline-offset-0 focus:outline-accent"
                />
                <textarea
                  placeholder="Note content (supports markdown)"
                  value={noteContent}
                  onChange={(e) => setNoteContent(e.target.value)}
                  rows={4}
                  className="w-full px-3 py-2 bg-white dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-700 rounded-lg text-sm text-neutral-700 dark:text-neutral-300 placeholder-neutral-500 dark:placeholder-neutral-400 focus:outline-2 focus:outline-offset-0 focus:outline-accent resize-none"
                />
                <div className="flex gap-2 justify-end">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      setIsAddingNote(false);
                      setNoteTitle('');
                      setNoteContent('');
                    }}
                  >
                    Cancel
                  </Button>
                  <Button
                    size="sm"
                    onClick={handleAddNote}
                    disabled={!noteTitle.trim() || !noteContent.trim()}
                  >
                    Save Note
                  </Button>
                </div>
              </CardBody>
            </Card>
          )}
        </>
      )}

      {/* Notes List */}
      <div className="space-y-3">
        {regularNotes.length > 0 ? (
          regularNotes.map((note) => {
            const isExpanded = expandedNotes.has(note.id);
            const preview = note.content.split('\n')[0];
            const isLong = note.content.length > 150;

            return (
              <Card key={note.id} className="hover:shadow-md transition-shadow">
                <div className="p-4">
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <div className="flex-1">
                      <h4 className="font-medium text-neutral-900 dark:text-neutral-50">
                        {note.title}
                      </h4>
                      <p className="text-xs text-neutral-500 dark:text-neutral-400">
                        {note.author} • {note.timestamp}
                      </p>
                    </div>
                    {!readonly && (
                      <button
                        aria-label="Delete note"
                        onClick={() => onDeleteNote?.(note.id)}
                        className="text-neutral-400 hover:text-danger transition-colors"
                      >
                        ✕
                      </button>
                    )}
                  </div>

                  <div className="mb-3">
                    <p className="text-sm text-neutral-700 dark:text-neutral-300">
                      {isExpanded ? note.content : preview}
                    </p>
                    {isLong && (
                      <button
                        onClick={() => toggleExpanded(note.id)}
                        className="text-xs text-accent hover:text-accent/80 font-medium mt-2"
                      >
                        {isExpanded ? 'Show less' : 'Show more'}
                      </button>
                    )}
                  </div>

                  {note.tags && note.tags.length > 0 && (
                    <div className="flex gap-2 flex-wrap">
                      {note.tags.map((tag) => (
                        <Badge key={tag} variant="info" className="text-xs">
                          {tag}
                        </Badge>
                      ))}
                    </div>
                  )}
                </div>
              </Card>
            );
          })
        ) : (
          <div className="text-center py-8 text-neutral-500 dark:text-neutral-400">
            <p className="text-sm">
              {readonly ? 'No notes available.' : 'No notes yet. Add one to get started!'}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
